# Run with `cmake -DSOURCE_DIR=... -DOUTPUT=... -P build-info.cmake` (on every build)
# Writes a header defining WEBCLAP_BUILD, e.g. "2026-10-10 5bb8ddd": the date and short ID of the
# latest commit, with a "+" after the ID if there are uncommitted changes.

set(build "unknown")
find_package(Git QUIET)
if (GIT_FOUND)
	execute_process(
		COMMAND ${GIT_EXECUTABLE} log -1 --format=%cs\ %h
		WORKING_DIRECTORY ${SOURCE_DIR}
		OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE
		RESULT_VARIABLE result ERROR_QUIET
	)
	if (result EQUAL 0 AND commit)
		set(build "${commit}")
		execute_process(
			COMMAND ${GIT_EXECUTABLE} status --porcelain --untracked-files=no
			WORKING_DIRECTORY ${SOURCE_DIR}
			OUTPUT_VARIABLE changes OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
		)
		if (changes)
			string(APPEND build "+")
		endif()
	endif()
endif()

set(content "// Generated by cmake/build-info.cmake - do not edit\n#pragma once\n#define WEBCLAP_BUILD \"${build}\"\n")
set(existing "")
if (EXISTS ${OUTPUT})
	file(READ ${OUTPUT} existing)
endif()
if (NOT content STREQUAL existing)
	file(WRITE ${OUTPUT} "${content}")
endif()
